"""SH-05: AES-GCM nonce strategy verification.

Verifies that:
- Nonces are generated by CSPRNG (os.urandom), never a counter.
- Nonce length is exactly 12 bytes (96 bits) per NIST SP 800-38D recommendation.
- 10 000 nonces under the same key produce no collisions.
- Nonce is stored as the first NONCE_SIZE bytes of the encrypted blob in
  LocalStateCipher and as a separate field in RecordCipher.
"""

import os

from cryptography.hazmat.primitives.ciphers.aead import AESGCM

from phasmid.crypto_params import AESGCM_KEY_SIZE, AESGCM_NONCE_SIZE
from phasmid.record_cypher import RecordCipher


class TestNonceLength:
    def test_record_cipher_nonce_size_constant(self):
        assert RecordCipher.NONCE_SIZE == 12

    def test_crypto_params_nonce_size(self):
        assert AESGCM_NONCE_SIZE == 12

    def test_generated_nonce_length(self):
        nonce = os.urandom(AESGCM_NONCE_SIZE)
        assert len(nonce) == 12


class TestNonceUniqueness:
    """10 000 random nonces under the same key must be unique (collision test)."""

    SAMPLE_COUNT = 10_000

    def test_no_nonce_collisions(self):
        nonces = {os.urandom(AESGCM_NONCE_SIZE) for _ in range(self.SAMPLE_COUNT)}
        assert len(nonces) == self.SAMPLE_COUNT, (
            f"Expected {self.SAMPLE_COUNT} unique nonces, got {len(nonces)}"
        )

    def test_encrypt_decrypt_roundtrip_unique_nonces(self):
        key = os.urandom(AESGCM_KEY_SIZE)
        aesgcm = AESGCM(key)
        plaintext = b"test payload"
        nonces_seen: set[bytes] = set()

        for _ in range(100):
            nonce = os.urandom(AESGCM_NONCE_SIZE)
            assert nonce not in nonces_seen, "Nonce reuse detected"
            nonces_seen.add(nonce)
            ct = aesgcm.encrypt(nonce, plaintext, None)
            assert aesgcm.decrypt(nonce, ct, None) == plaintext


class TestLocalStateCipherNonceLayout:
    """LocalStateCipher prepends a 12-byte nonce to every ciphertext blob."""

    def test_encrypted_blob_starts_with_nonce(self, tmp_path):
        from phasmid.local_state_crypto import LocalStateCipher

        cipher = LocalStateCipher(
            state_key_path=str(tmp_path / "state.key"),
            aad=b"test-aad",
        )
        blob = cipher.encrypt(b"hello")
        assert len(blob) > AESGCM_NONCE_SIZE
        # First 12 bytes are the nonce; remaining bytes are the ciphertext+tag.
        nonce = blob[:AESGCM_NONCE_SIZE]
        assert len(nonce) == AESGCM_NONCE_SIZE

    def test_decrypt_after_encrypt(self, tmp_path):
        from phasmid.local_state_crypto import LocalStateCipher

        cipher = LocalStateCipher(
            state_key_path=str(tmp_path / "state.key"),
            aad=b"test-aad",
        )
        plaintext = b"round-trip test"
        blob = cipher.encrypt(plaintext)
        recovered = cipher.decrypt(
            blob,
            too_short_message="too short",
            auth_failed_message="auth failed",
        )
        assert recovered == plaintext
